### ISSUE TITLE
stolen tokens

### ISSUE THREAD

**Issue by Saaditto** [Steemhunt/mint.club-contract#1]
who lost their mint tokens on the trust wallet. the transfer went through without validation on my part

Transaction : 
https://bscscan.com/tx/0x3a57885bb7793395721339a1f1ce4e186b02735bcfbadc06a5ee2097fdf81d4e

**Comment by sydneyitguy** [comment]
Not a contract issue. I guess you should check if your private key or seed phrase is leaked.
